# Generated by Django 3.2.5 on 2021-07-17 22:51

import craig_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[craig_app.models.validate_category_name_presence])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='craig_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[craig_app.models.validate_post_title_presence])),
                ('description', models.CharField(max_length=1000, validators=[craig_app.models.validate_post_description_presence])),
                ('created_at', models.DateTimeField(auto_now_add=True, validators=[craig_app.models.validate_created])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='craig_app.category')),
            ],
        ),
    ]
