# Generated by Django 3.2.5 on 2021-07-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craig_app', '0002_alter_category_parent_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='craig_app.category'),
        ),
    ]
